[package]
name = "noiselib"
version = "0.0.1"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits = "^0.2.14"

[dev-dependencies]
image = "^0.23.14"
rand = "^0.8.4"